2024-01-24 16:47:30,126 ERROR frappe New Exception collected in error log
Site: hilltop
Form Dict: {}
2024-01-24 16:56:26,128 ERROR frappe New Exception collected in error log
Site: hilltop
Form Dict: {}
2024-01-24 16:56:26,257 ERROR frappe New Exception collected in error log
Site: hilltop
Form Dict: {}
2024-01-24 16:56:35,373 ERROR frappe New Exception collected in error log
Site: hilltop
Form Dict: {}
2024-01-24 16:56:35,489 ERROR frappe New Exception collected in error log
Site: hilltop
Form Dict: {}
2024-01-24 16:56:38,280 ERROR frappe New Exception collected in error log
Site: hilltop
Form Dict: {}
2024-01-24 16:56:38,396 ERROR frappe New Exception collected in error log
Site: hilltop
Form Dict: {}
2024-01-24 17:01:06,006 ERROR frappe New Exception collected in error log
Site: hilltop
Form Dict: {}
2024-01-24 17:01:06,762 ERROR frappe New Exception collected in error log
Site: hilltop
Form Dict: {}
2024-01-24 17:01:06,927 ERROR frappe New Exception collected in error log
Site: hilltop
Form Dict: {}
2024-01-24 17:01:07,065 ERROR frappe New Exception collected in error log
Site: hilltop
Form Dict: {}
2024-01-24 17:01:08,957 ERROR frappe New Exception collected in error log
Site: hilltop
Form Dict: {}
2024-01-24 17:01:09,187 ERROR frappe New Exception collected in error log
Site: hilltop
Form Dict: {}
2024-01-24 17:01:09,360 ERROR frappe New Exception collected in error log
Site: hilltop
Form Dict: {}
2024-01-24 17:01:09,510 ERROR frappe New Exception collected in error log
Site: hilltop
Form Dict: {}
2024-01-24 17:01:32,905 ERROR frappe New Exception collected in error log
Site: hilltop
Form Dict: {}
2024-01-24 17:01:33,090 ERROR frappe New Exception collected in error log
Site: hilltop
Form Dict: {}
2024-01-24 17:01:36,383 ERROR frappe New Exception collected in error log
Site: hilltop
Form Dict: {}
2024-01-24 17:01:36,594 ERROR frappe New Exception collected in error log
Site: hilltop
Form Dict: {}
2024-01-24 17:01:38,217 ERROR frappe New Exception collected in error log
Site: hilltop
Form Dict: {}
2024-01-24 17:01:38,353 ERROR frappe New Exception collected in error log
Site: hilltop
Form Dict: {}
2024-01-24 17:01:39,319 ERROR frappe New Exception collected in error log
Site: hilltop
Form Dict: {}
2024-01-24 17:01:39,440 ERROR frappe New Exception collected in error log
Site: hilltop
Form Dict: {}
2024-01-24 17:01:45,488 ERROR frappe New Exception collected in error log
Site: hilltop
Form Dict: {}
2024-01-24 17:01:45,594 ERROR frappe New Exception collected in error log
Site: hilltop
Form Dict: {}
2024-01-24 17:01:46,443 ERROR frappe New Exception collected in error log
Site: hilltop
Form Dict: {}
2024-01-24 17:01:46,565 ERROR frappe New Exception collected in error log
Site: hilltop
Form Dict: {}
2024-01-24 17:02:18,642 ERROR frappe New Exception collected in error log
Site: hilltop
Form Dict: {}
2024-01-24 17:02:18,759 ERROR frappe New Exception collected in error log
Site: hilltop
Form Dict: {}
2024-01-24 17:02:51,554 ERROR frappe New Exception collected in error log
Site: hilltop
Form Dict: {}
2024-01-24 17:02:51,678 ERROR frappe New Exception collected in error log
Site: hilltop
Form Dict: {}
2024-01-24 17:02:52,609 ERROR frappe New Exception collected in error log
Site: hilltop
Form Dict: {}
2024-01-24 17:02:52,746 ERROR frappe New Exception collected in error log
Site: hilltop
Form Dict: {}
2024-01-24 17:02:52,975 ERROR frappe New Exception collected in error log
Site: hilltop
Form Dict: {}
2024-01-24 17:02:53,119 ERROR frappe New Exception collected in error log
Site: hilltop
Form Dict: {}
2024-01-24 17:03:07,382 ERROR frappe New Exception collected in error log
Site: hilltop
Form Dict: {}
2024-01-24 17:03:07,525 ERROR frappe New Exception collected in error log
Site: hilltop
Form Dict: {}
2024-01-24 17:03:10,839 ERROR frappe New Exception collected in error log
Site: hilltop
Form Dict: {}
2024-01-24 17:03:11,074 ERROR frappe New Exception collected in error log
Site: hilltop
Form Dict: {}
2024-01-24 17:04:52,102 ERROR frappe New Exception collected in error log
Site: hilltop
Form Dict: {}
2024-01-24 17:04:52,222 ERROR frappe New Exception collected in error log
Site: hilltop
Form Dict: {}
2024-01-24 17:04:53,256 ERROR frappe New Exception collected in error log
Site: hilltop
Form Dict: {}
2024-01-24 17:04:53,377 ERROR frappe New Exception collected in error log
Site: hilltop
Form Dict: {}
2024-01-24 17:04:54,495 ERROR frappe New Exception collected in error log
Site: hilltop
Form Dict: {}
2024-01-24 17:04:54,615 ERROR frappe New Exception collected in error log
Site: hilltop
Form Dict: {}
2024-01-24 17:04:56,148 ERROR frappe New Exception collected in error log
Site: hilltop
Form Dict: {}
2024-01-24 17:04:56,263 ERROR frappe New Exception collected in error log
Site: hilltop
Form Dict: {}
2024-01-24 19:16:51,720 ERROR frappe New Exception collected in error log
Site: hilltop
Form Dict: {}
2024-01-24 19:16:51,863 ERROR frappe New Exception collected in error log
Site: hilltop
Form Dict: {}
2024-01-24 19:16:53,915 ERROR frappe New Exception collected in error log
Site: hilltop
Form Dict: {}
2024-01-24 19:16:54,045 ERROR frappe New Exception collected in error log
Site: hilltop
Form Dict: {}
2024-01-24 19:16:55,384 ERROR frappe New Exception collected in error log
Site: hilltop
Form Dict: {}
2024-01-24 19:16:55,509 ERROR frappe New Exception collected in error log
Site: hilltop
Form Dict: {}
2024-01-24 19:17:08,996 ERROR frappe New Exception collected in error log
Site: hilltop
Form Dict: {}
2024-01-24 19:17:09,115 ERROR frappe New Exception collected in error log
Site: hilltop
Form Dict: {}
2024-01-24 19:17:10,241 ERROR frappe New Exception collected in error log
Site: hilltop
Form Dict: {}
2024-01-24 19:17:10,359 ERROR frappe New Exception collected in error log
Site: hilltop
Form Dict: {}
2024-01-24 19:18:11,885 ERROR frappe New Exception collected in error log
Site: hilltop
Form Dict: {}
2024-01-24 19:18:12,010 ERROR frappe New Exception collected in error log
Site: hilltop
Form Dict: {}
2024-01-24 19:18:13,075 ERROR frappe New Exception collected in error log
Site: hilltop
Form Dict: {}
2024-01-24 19:18:13,204 ERROR frappe New Exception collected in error log
Site: hilltop
Form Dict: {}
2024-01-24 19:18:16,638 ERROR frappe New Exception collected in error log
Site: hilltop
Form Dict: {}
2024-01-24 19:18:16,787 ERROR frappe New Exception collected in error log
Site: hilltop
Form Dict: {}
2024-01-25 16:13:52,335 ERROR frappe New Exception collected in error log
Site: hilltop
Form Dict: {}
2024-01-25 16:13:52,336 ERROR frappe New Exception collected in error log
Site: hilltop
Form Dict: {}
2024-01-25 16:13:52,721 ERROR frappe New Exception collected in error log
Site: hilltop
Form Dict: {}
2024-01-25 16:13:59,371 ERROR frappe New Exception collected in error log
Site: hilltop
Form Dict: {}
2024-01-25 16:13:59,592 ERROR frappe New Exception collected in error log
Site: hilltop
Form Dict: {}
2024-01-25 16:14:02,407 ERROR frappe New Exception collected in error log
Site: hilltop
Form Dict: {}
2024-01-25 16:14:02,588 ERROR frappe New Exception collected in error log
Site: hilltop
Form Dict: {}
2024-01-25 16:14:03,475 ERROR frappe New Exception collected in error log
Site: hilltop
Form Dict: {}
2024-01-25 16:14:03,700 ERROR frappe New Exception collected in error log
Site: hilltop
Form Dict: {}
2024-01-25 16:14:04,040 ERROR frappe New Exception collected in error log
Site: hilltop
Form Dict: {}
2024-01-25 16:14:04,224 ERROR frappe New Exception collected in error log
Site: hilltop
Form Dict: {}
2024-01-25 16:14:04,646 ERROR frappe New Exception collected in error log
Site: hilltop
Form Dict: {}
2024-01-25 16:14:04,871 ERROR frappe New Exception collected in error log
Site: hilltop
Form Dict: {}
2024-01-25 16:14:05,047 ERROR frappe New Exception collected in error log
Site: hilltop
Form Dict: {}
2024-01-25 16:14:05,251 ERROR frappe New Exception collected in error log
Site: hilltop
Form Dict: {}
2024-01-25 16:14:05,558 ERROR frappe New Exception collected in error log
Site: hilltop
Form Dict: {}
2024-01-25 16:14:05,694 ERROR frappe New Exception collected in error log
Site: hilltop
Form Dict: {}
2024-01-25 16:14:06,727 ERROR frappe New Exception collected in error log
Site: hilltop
Form Dict: {}
2024-01-25 16:14:06,845 ERROR frappe New Exception collected in error log
Site: hilltop
Form Dict: {}
2024-01-25 16:14:21,610 ERROR frappe New Exception collected in error log
Site: hilltop
Form Dict: {}
2024-01-25 16:14:21,743 ERROR frappe New Exception collected in error log
Site: hilltop
Form Dict: {}
2024-01-25 16:54:02,399 ERROR frappe New Exception collected in error log
Site: hilltop
Form Dict: {}
2024-01-25 16:54:02,618 ERROR frappe New Exception collected in error log
Site: hilltop
Form Dict: {}
2024-01-25 16:54:05,005 ERROR frappe New Exception collected in error log
Site: hilltop
Form Dict: {}
2024-01-25 16:54:05,160 ERROR frappe New Exception collected in error log
Site: hilltop
Form Dict: {}
2024-01-25 16:54:06,105 ERROR frappe New Exception collected in error log
Site: hilltop
Form Dict: {}
2024-01-25 16:54:06,264 ERROR frappe New Exception collected in error log
Site: hilltop
Form Dict: {}
2024-01-25 16:54:07,688 ERROR frappe New Exception collected in error log
Site: hilltop
Form Dict: {}
2024-01-25 16:54:07,892 ERROR frappe New Exception collected in error log
Site: hilltop
Form Dict: {}
2024-01-25 16:54:27,430 ERROR frappe New Exception collected in error log
Site: hilltop
Form Dict: {}
2024-01-25 16:54:27,608 ERROR frappe New Exception collected in error log
Site: hilltop
Form Dict: {}
2024-01-25 16:54:59,089 ERROR frappe New Exception collected in error log
Site: hilltop
Form Dict: {}
2024-01-25 16:54:59,248 ERROR frappe New Exception collected in error log
Site: hilltop
Form Dict: {}
2024-01-25 19:27:15,751 ERROR frappe New Exception collected in error log
Site: hilltop
Form Dict: {}
2024-01-25 19:27:16,704 ERROR frappe New Exception collected in error log
Site: hilltop
Form Dict: {}
2024-01-25 19:27:17,117 ERROR frappe New Exception collected in error log
Site: hilltop
Form Dict: {}
2024-01-25 19:27:17,118 ERROR frappe New Exception collected in error log
Site: hilltop
Form Dict: {}
2024-01-25 19:27:17,126 ERROR frappe New Exception collected in error log
Site: hilltop
Form Dict: {}
2024-01-25 19:27:17,142 ERROR frappe New Exception collected in error log
Site: hilltop
Form Dict: {}
2024-01-25 19:27:17,291 ERROR frappe New Exception collected in error log
Site: hilltop
Form Dict: {}
2024-01-25 19:27:17,403 ERROR frappe New Exception collected in error log
Site: hilltop
Form Dict: {}
2024-01-25 19:27:20,384 ERROR frappe New Exception collected in error log
Site: hilltop
Form Dict: {}
2024-01-25 19:27:20,526 ERROR frappe New Exception collected in error log
Site: hilltop
Form Dict: {}
2024-01-25 19:27:22,215 ERROR frappe New Exception collected in error log
Site: hilltop
Form Dict: {}
2024-01-25 19:27:22,342 ERROR frappe New Exception collected in error log
Site: hilltop
Form Dict: {}
2024-01-27 13:30:51,723 ERROR frappe Failed to run after request hook
Site: hilltop
Form Dict: {}
Traceback (most recent call last):
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/app.py", line 95, in application
    init_request(request)
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/app.py", line 179, in init_request
    raise frappe.SessionStopped("Session Stopped")
frappe.exceptions.SessionStopped: Session Stopped

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/website/serve.py", line 17, in get_response
    endpoint, renderer_instance = path_resolver.resolve()
                                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/website/path_resolver.py", line 37, in resolve
    resolve_redirect(self.path, request.query_string)
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/website/path_resolver.py", line 111, in resolve_redirect
    redirects = frappe.get_hooks("website_redirects")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/__init__.py", line 1573, in get_hooks
    hooks = _dict(_load_app_hooks())
                  ^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/__init__.py", line 1542, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/__init__.py", line 1408, in get_module
    return importlib.import_module(modulename)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'custom_app.hooks'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/app.py", line 128, in application
    response = handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/app.py", line 334, in handle_exception
    response = frappe.utils.response.handle_session_stopped()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/utils/response.py", line 327, in handle_session_stopped
    return get_response("message", http_status_code=503)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/website/serve.py", line 26, in get_response
    response = ErrorPage(exception=e).render()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/website/page_renderers/template_page.py", line 84, in render
    html = self.get_html()
           ^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/website/utils.py", line 524, in cache_html_decorator
    html = func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/website/page_renderers/template_page.py", line 92, in get_html
    self.init_context()
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/website/page_renderers/error_page.py", line 14, in init_context
    super().init_context()
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/website/page_renderers/base_template_page.py", line 15, in init_context
    self.context.update(get_website_settings())
                        ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/website/doctype/website_settings/website_settings.py", line 172, in get_website_settings
    hooks = frappe.get_hooks()
            ^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/__init__.py", line 1573, in get_hooks
    hooks = _dict(_load_app_hooks())
                  ^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/__init__.py", line 1542, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/__init__.py", line 1408, in get_module
    return importlib.import_module(modulename)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'custom_app.hooks'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/app.py", line 142, in application
    run_after_request_hooks(request, response)
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/app.py", line 157, in run_after_request_hooks
    for after_request_task in frappe.get_hooks("after_request"):
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/__init__.py", line 1573, in get_hooks
    hooks = _dict(_load_app_hooks())
                  ^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/__init__.py", line 1542, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/__init__.py", line 1408, in get_module
    return importlib.import_module(modulename)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'custom_app.hooks'
2024-01-27 13:30:51,794 ERROR frappe Could not take error snapshot: No module named 'custom_app.hooks'
Site: hilltop
Form Dict: {}
Traceback (most recent call last):
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/app.py", line 95, in application
    init_request(request)
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/app.py", line 179, in init_request
    raise frappe.SessionStopped("Session Stopped")
frappe.exceptions.SessionStopped: Session Stopped

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/utils/error.py", line 89, in log_error_snapshot
    log_error(title=str(exception), defer_insert=True)
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/utils/error.py", line 63, in log_error
    error_log = frappe.get_doc(
                ^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/__init__.py", line 1265, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/model/document.py", line 80, in get_doc
    controller = get_controller(doctype)
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/model/base_document.py", line 66, in get_controller
    return import_controller(doctype)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/model/base_document.py", line 88, in import_controller
    class_overrides = frappe.get_hooks("override_doctype_class")
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/__init__.py", line 1573, in get_hooks
    hooks = _dict(_load_app_hooks())
                  ^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/__init__.py", line 1542, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/__init__.py", line 1408, in get_module
    return importlib.import_module(modulename)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'custom_app.hooks'
2024-01-27 13:30:51,798 ERROR frappe Failed to run after request hook
Site: hilltop
Form Dict: {}
Traceback (most recent call last):
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/app.py", line 142, in application
    run_after_request_hooks(request, response)
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/app.py", line 157, in run_after_request_hooks
    for after_request_task in frappe.get_hooks("after_request"):
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/__init__.py", line 1573, in get_hooks
    hooks = _dict(_load_app_hooks())
                  ^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/__init__.py", line 1542, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/__init__.py", line 1408, in get_module
    return importlib.import_module(modulename)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'custom_app.hooks'
2024-01-27 13:34:06,490 ERROR frappe Failed to run after request hook
Site: hilltop
Form Dict: {}
Traceback (most recent call last):
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/app.py", line 95, in application
    init_request(request)
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/app.py", line 179, in init_request
    raise frappe.SessionStopped("Session Stopped")
frappe.exceptions.SessionStopped: Session Stopped

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/app.py", line 128, in application
    response = handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/app.py", line 320, in handle_exception
    allow_traceback = frappe.get_system_settings("allow_error_traceback") if frappe.db else False
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/__init__.py", line 2300, in get_system_settings
    local.system_settings = get_cached_doc("System Settings")
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/__init__.py", line 1137, in get_cached_doc
    doc = get_doc(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/__init__.py", line 1265, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/model/document.py", line 80, in get_doc
    controller = get_controller(doctype)
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/model/base_document.py", line 66, in get_controller
    return import_controller(doctype)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/model/base_document.py", line 88, in import_controller
    class_overrides = frappe.get_hooks("override_doctype_class")
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/__init__.py", line 1573, in get_hooks
    hooks = _dict(_load_app_hooks())
                  ^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/__init__.py", line 1542, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/__init__.py", line 1408, in get_module
    return importlib.import_module(modulename)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'custom_app.hooks'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/app.py", line 142, in application
    run_after_request_hooks(request, response)
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/app.py", line 157, in run_after_request_hooks
    for after_request_task in frappe.get_hooks("after_request"):
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/__init__.py", line 1573, in get_hooks
    hooks = _dict(_load_app_hooks())
                  ^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/__init__.py", line 1542, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/__init__.py", line 1408, in get_module
    return importlib.import_module(modulename)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'custom_app.hooks'
2024-01-27 13:34:07,220 ERROR frappe Failed to run after request hook
Site: hilltop
Form Dict: {}
Traceback (most recent call last):
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/app.py", line 95, in application
    init_request(request)
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/app.py", line 179, in init_request
    raise frappe.SessionStopped("Session Stopped")
frappe.exceptions.SessionStopped: Session Stopped

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/app.py", line 128, in application
    response = handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/app.py", line 320, in handle_exception
    allow_traceback = frappe.get_system_settings("allow_error_traceback") if frappe.db else False
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/__init__.py", line 2300, in get_system_settings
    local.system_settings = get_cached_doc("System Settings")
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/__init__.py", line 1137, in get_cached_doc
    doc = get_doc(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/__init__.py", line 1265, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/model/document.py", line 80, in get_doc
    controller = get_controller(doctype)
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/model/base_document.py", line 66, in get_controller
    return import_controller(doctype)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/model/base_document.py", line 88, in import_controller
    class_overrides = frappe.get_hooks("override_doctype_class")
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/__init__.py", line 1573, in get_hooks
    hooks = _dict(_load_app_hooks())
                  ^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/__init__.py", line 1542, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/__init__.py", line 1408, in get_module
    return importlib.import_module(modulename)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'custom_app.hooks'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/app.py", line 142, in application
    run_after_request_hooks(request, response)
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/app.py", line 157, in run_after_request_hooks
    for after_request_task in frappe.get_hooks("after_request"):
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/__init__.py", line 1573, in get_hooks
    hooks = _dict(_load_app_hooks())
                  ^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/__init__.py", line 1542, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/__init__.py", line 1408, in get_module
    return importlib.import_module(modulename)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'custom_app.hooks'
2024-01-27 13:34:07,751 ERROR frappe Failed to run after request hook
Site: hilltop
Form Dict: {}
Traceback (most recent call last):
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/app.py", line 95, in application
    init_request(request)
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/app.py", line 179, in init_request
    raise frappe.SessionStopped("Session Stopped")
frappe.exceptions.SessionStopped: Session Stopped

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/app.py", line 128, in application
    response = handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/app.py", line 320, in handle_exception
    allow_traceback = frappe.get_system_settings("allow_error_traceback") if frappe.db else False
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/__init__.py", line 2300, in get_system_settings
    local.system_settings = get_cached_doc("System Settings")
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/__init__.py", line 1137, in get_cached_doc
    doc = get_doc(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/__init__.py", line 1265, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/model/document.py", line 80, in get_doc
    controller = get_controller(doctype)
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/model/base_document.py", line 66, in get_controller
    return import_controller(doctype)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/model/base_document.py", line 88, in import_controller
    class_overrides = frappe.get_hooks("override_doctype_class")
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/__init__.py", line 1573, in get_hooks
    hooks = _dict(_load_app_hooks())
                  ^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/__init__.py", line 1542, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/__init__.py", line 1408, in get_module
    return importlib.import_module(modulename)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'custom_app.hooks'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/app.py", line 142, in application
    run_after_request_hooks(request, response)
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/app.py", line 157, in run_after_request_hooks
    for after_request_task in frappe.get_hooks("after_request"):
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/__init__.py", line 1573, in get_hooks
    hooks = _dict(_load_app_hooks())
                  ^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/__init__.py", line 1542, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/__init__.py", line 1408, in get_module
    return importlib.import_module(modulename)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'custom_app.hooks'
2024-01-27 13:34:07,916 ERROR frappe Failed to run after request hook
Site: hilltop
Form Dict: {}
Traceback (most recent call last):
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/app.py", line 95, in application
    init_request(request)
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/app.py", line 179, in init_request
    raise frappe.SessionStopped("Session Stopped")
frappe.exceptions.SessionStopped: Session Stopped

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/app.py", line 128, in application
    response = handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/app.py", line 320, in handle_exception
    allow_traceback = frappe.get_system_settings("allow_error_traceback") if frappe.db else False
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/__init__.py", line 2300, in get_system_settings
    local.system_settings = get_cached_doc("System Settings")
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/__init__.py", line 1137, in get_cached_doc
    doc = get_doc(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/__init__.py", line 1265, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/model/document.py", line 80, in get_doc
    controller = get_controller(doctype)
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/model/base_document.py", line 66, in get_controller
    return import_controller(doctype)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/model/base_document.py", line 88, in import_controller
    class_overrides = frappe.get_hooks("override_doctype_class")
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/__init__.py", line 1573, in get_hooks
    hooks = _dict(_load_app_hooks())
                  ^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/__init__.py", line 1542, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/__init__.py", line 1408, in get_module
    return importlib.import_module(modulename)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'custom_app.hooks'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/app.py", line 142, in application
    run_after_request_hooks(request, response)
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/app.py", line 157, in run_after_request_hooks
    for after_request_task in frappe.get_hooks("after_request"):
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/__init__.py", line 1573, in get_hooks
    hooks = _dict(_load_app_hooks())
                  ^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/__init__.py", line 1542, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/__init__.py", line 1408, in get_module
    return importlib.import_module(modulename)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'custom_app.hooks'
2024-01-27 13:34:08,075 ERROR frappe Failed to run after request hook
Site: hilltop
Form Dict: {}
Traceback (most recent call last):
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/app.py", line 95, in application
    init_request(request)
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/app.py", line 179, in init_request
    raise frappe.SessionStopped("Session Stopped")
frappe.exceptions.SessionStopped: Session Stopped

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/app.py", line 128, in application
    response = handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/app.py", line 320, in handle_exception
    allow_traceback = frappe.get_system_settings("allow_error_traceback") if frappe.db else False
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/__init__.py", line 2300, in get_system_settings
    local.system_settings = get_cached_doc("System Settings")
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/__init__.py", line 1137, in get_cached_doc
    doc = get_doc(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/__init__.py", line 1265, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/model/document.py", line 80, in get_doc
    controller = get_controller(doctype)
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/model/base_document.py", line 66, in get_controller
    return import_controller(doctype)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/model/base_document.py", line 88, in import_controller
    class_overrides = frappe.get_hooks("override_doctype_class")
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/__init__.py", line 1573, in get_hooks
    hooks = _dict(_load_app_hooks())
                  ^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/__init__.py", line 1542, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/__init__.py", line 1408, in get_module
    return importlib.import_module(modulename)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'custom_app.hooks'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/app.py", line 142, in application
    run_after_request_hooks(request, response)
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/app.py", line 157, in run_after_request_hooks
    for after_request_task in frappe.get_hooks("after_request"):
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/__init__.py", line 1573, in get_hooks
    hooks = _dict(_load_app_hooks())
                  ^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/__init__.py", line 1542, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/__init__.py", line 1408, in get_module
    return importlib.import_module(modulename)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'custom_app.hooks'
2024-01-27 13:34:08,288 ERROR frappe Failed to run after request hook
Site: hilltop
Form Dict: {}
Traceback (most recent call last):
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/app.py", line 95, in application
    init_request(request)
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/app.py", line 179, in init_request
    raise frappe.SessionStopped("Session Stopped")
frappe.exceptions.SessionStopped: Session Stopped

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/app.py", line 128, in application
    response = handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/app.py", line 320, in handle_exception
    allow_traceback = frappe.get_system_settings("allow_error_traceback") if frappe.db else False
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/__init__.py", line 2300, in get_system_settings
    local.system_settings = get_cached_doc("System Settings")
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/__init__.py", line 1137, in get_cached_doc
    doc = get_doc(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/__init__.py", line 1265, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/model/document.py", line 80, in get_doc
    controller = get_controller(doctype)
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/model/base_document.py", line 66, in get_controller
    return import_controller(doctype)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/model/base_document.py", line 88, in import_controller
    class_overrides = frappe.get_hooks("override_doctype_class")
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/__init__.py", line 1573, in get_hooks
    hooks = _dict(_load_app_hooks())
                  ^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/__init__.py", line 1542, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/__init__.py", line 1408, in get_module
    return importlib.import_module(modulename)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'custom_app.hooks'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/app.py", line 142, in application
    run_after_request_hooks(request, response)
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/app.py", line 157, in run_after_request_hooks
    for after_request_task in frappe.get_hooks("after_request"):
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/__init__.py", line 1573, in get_hooks
    hooks = _dict(_load_app_hooks())
                  ^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/__init__.py", line 1542, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/__init__.py", line 1408, in get_module
    return importlib.import_module(modulename)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'custom_app.hooks'
2024-01-29 17:01:36,950 ERROR frappe Failed to run after request hook
Site: hilltop
Form Dict: {'module': 'customapp'}
Traceback (most recent call last):
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/app.py", line 95, in application
    init_request(request)
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/app.py", line 191, in init_request
    frappe.local.http_request = HTTPRequest()
                                ^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/auth.py", line 40, in __init__
    self.set_session()
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/auth.py", line 76, in set_session
    frappe.local.login_manager = LoginManager()
                                 ^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/auth.py", line 121, in __init__
    self.make_session(resume=True)
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/auth.py", line 209, in make_session
    frappe.local.session_obj = Session(
                               ^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/sessions.py", line 215, in __init__
    self.resume()
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/sessions.py", line 281, in resume
    data = self.get_session_record()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/sessions.py", line 298, in get_session_record
    r = self.get_session_data()
        ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/sessions.py", line 314, in get_session_data
    data = self.get_session_data_from_db()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/sessions.py", line 342, in get_session_data_from_db
    .where(sessions.lastupdate > get_expired_threshold())
                                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/sessions.py", line 419, in get_expired_threshold
    now = frappe.utils.now()
          ^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/utils/data.py", line 351, in now
    return now_datetime().strftime(DATETIME_FORMAT)
           ^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/utils/data.py", line 298, in now_datetime
    dt = convert_utc_to_system_timezone(datetime.datetime.utcnow())
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/utils/data.py", line 338, in convert_utc_to_system_timezone
    time_zone = get_system_timezone()
                ^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/utils/data.py", line 319, in get_system_timezone
    return frappe.cache.get_value("time_zone", _get_system_timezone)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/utils/redis_wrapper.py", line 100, in get_value
    val = generator()
          ^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/utils/data.py", line 312, in _get_system_timezone
    return frappe.get_system_settings("time_zone") or "Asia/Kolkata"  # Default to India ?!
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/__init__.py", line 2300, in get_system_settings
    local.system_settings = get_cached_doc("System Settings")
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/__init__.py", line 1137, in get_cached_doc
    doc = get_doc(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/__init__.py", line 1265, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/model/document.py", line 80, in get_doc
    controller = get_controller(doctype)
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/model/base_document.py", line 66, in get_controller
    return import_controller(doctype)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/model/base_document.py", line 88, in import_controller
    class_overrides = frappe.get_hooks("override_doctype_class")
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/__init__.py", line 1573, in get_hooks
    hooks = _dict(_load_app_hooks())
                  ^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/__init__.py", line 1542, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/__init__.py", line 1408, in get_module
    return importlib.import_module(modulename)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'hilltop.hooks'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/app.py", line 128, in application
    response = handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/app.py", line 320, in handle_exception
    allow_traceback = frappe.get_system_settings("allow_error_traceback") if frappe.db else False
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/__init__.py", line 2300, in get_system_settings
    local.system_settings = get_cached_doc("System Settings")
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/__init__.py", line 1137, in get_cached_doc
    doc = get_doc(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/__init__.py", line 1265, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/model/document.py", line 80, in get_doc
    controller = get_controller(doctype)
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/model/base_document.py", line 66, in get_controller
    return import_controller(doctype)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/model/base_document.py", line 88, in import_controller
    class_overrides = frappe.get_hooks("override_doctype_class")
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/__init__.py", line 1573, in get_hooks
    hooks = _dict(_load_app_hooks())
                  ^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/__init__.py", line 1542, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/__init__.py", line 1408, in get_module
    return importlib.import_module(modulename)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'hilltop.hooks'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/app.py", line 142, in application
    run_after_request_hooks(request, response)
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/app.py", line 157, in run_after_request_hooks
    for after_request_task in frappe.get_hooks("after_request"):
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/__init__.py", line 1573, in get_hooks
    hooks = _dict(_load_app_hooks())
                  ^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/__init__.py", line 1542, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/__init__.py", line 1408, in get_module
    return importlib.import_module(modulename)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'hilltop.hooks'
2024-01-29 17:01:38,774 ERROR frappe Failed to run after request hook
Site: hilltop
Form Dict: {'module': 'customapp'}
Traceback (most recent call last):
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/app.py", line 95, in application
    init_request(request)
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/app.py", line 191, in init_request
    frappe.local.http_request = HTTPRequest()
                                ^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/auth.py", line 40, in __init__
    self.set_session()
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/auth.py", line 76, in set_session
    frappe.local.login_manager = LoginManager()
                                 ^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/auth.py", line 121, in __init__
    self.make_session(resume=True)
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/auth.py", line 209, in make_session
    frappe.local.session_obj = Session(
                               ^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/sessions.py", line 215, in __init__
    self.resume()
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/sessions.py", line 281, in resume
    data = self.get_session_record()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/sessions.py", line 298, in get_session_record
    r = self.get_session_data()
        ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/sessions.py", line 314, in get_session_data
    data = self.get_session_data_from_db()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/sessions.py", line 342, in get_session_data_from_db
    .where(sessions.lastupdate > get_expired_threshold())
                                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/sessions.py", line 419, in get_expired_threshold
    now = frappe.utils.now()
          ^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/utils/data.py", line 351, in now
    return now_datetime().strftime(DATETIME_FORMAT)
           ^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/utils/data.py", line 298, in now_datetime
    dt = convert_utc_to_system_timezone(datetime.datetime.utcnow())
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/utils/data.py", line 338, in convert_utc_to_system_timezone
    time_zone = get_system_timezone()
                ^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/utils/data.py", line 319, in get_system_timezone
    return frappe.cache.get_value("time_zone", _get_system_timezone)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/utils/redis_wrapper.py", line 100, in get_value
    val = generator()
          ^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/utils/data.py", line 312, in _get_system_timezone
    return frappe.get_system_settings("time_zone") or "Asia/Kolkata"  # Default to India ?!
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/__init__.py", line 2300, in get_system_settings
    local.system_settings = get_cached_doc("System Settings")
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/__init__.py", line 1137, in get_cached_doc
    doc = get_doc(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/__init__.py", line 1265, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/model/document.py", line 80, in get_doc
    controller = get_controller(doctype)
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/model/base_document.py", line 66, in get_controller
    return import_controller(doctype)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/model/base_document.py", line 88, in import_controller
    class_overrides = frappe.get_hooks("override_doctype_class")
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/__init__.py", line 1573, in get_hooks
    hooks = _dict(_load_app_hooks())
                  ^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/__init__.py", line 1542, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/__init__.py", line 1408, in get_module
    return importlib.import_module(modulename)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'hilltop.hooks'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/app.py", line 128, in application
    response = handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/app.py", line 320, in handle_exception
    allow_traceback = frappe.get_system_settings("allow_error_traceback") if frappe.db else False
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/__init__.py", line 2300, in get_system_settings
    local.system_settings = get_cached_doc("System Settings")
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/__init__.py", line 1137, in get_cached_doc
    doc = get_doc(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/__init__.py", line 1265, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/model/document.py", line 80, in get_doc
    controller = get_controller(doctype)
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/model/base_document.py", line 66, in get_controller
    return import_controller(doctype)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/model/base_document.py", line 88, in import_controller
    class_overrides = frappe.get_hooks("override_doctype_class")
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/__init__.py", line 1573, in get_hooks
    hooks = _dict(_load_app_hooks())
                  ^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/__init__.py", line 1542, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/__init__.py", line 1408, in get_module
    return importlib.import_module(modulename)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'hilltop.hooks'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/app.py", line 142, in application
    run_after_request_hooks(request, response)
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/app.py", line 157, in run_after_request_hooks
    for after_request_task in frappe.get_hooks("after_request"):
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/__init__.py", line 1573, in get_hooks
    hooks = _dict(_load_app_hooks())
                  ^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/__init__.py", line 1542, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/__init__.py", line 1408, in get_module
    return importlib.import_module(modulename)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'hilltop.hooks'
2024-01-29 17:01:39,609 ERROR frappe Failed to run after request hook
Site: hilltop
Form Dict: {'module': 'customapp'}
Traceback (most recent call last):
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/app.py", line 95, in application
    init_request(request)
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/app.py", line 191, in init_request
    frappe.local.http_request = HTTPRequest()
                                ^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/auth.py", line 40, in __init__
    self.set_session()
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/auth.py", line 76, in set_session
    frappe.local.login_manager = LoginManager()
                                 ^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/auth.py", line 121, in __init__
    self.make_session(resume=True)
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/auth.py", line 209, in make_session
    frappe.local.session_obj = Session(
                               ^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/sessions.py", line 215, in __init__
    self.resume()
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/sessions.py", line 281, in resume
    data = self.get_session_record()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/sessions.py", line 298, in get_session_record
    r = self.get_session_data()
        ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/sessions.py", line 314, in get_session_data
    data = self.get_session_data_from_db()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/sessions.py", line 342, in get_session_data_from_db
    .where(sessions.lastupdate > get_expired_threshold())
                                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/sessions.py", line 419, in get_expired_threshold
    now = frappe.utils.now()
          ^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/utils/data.py", line 351, in now
    return now_datetime().strftime(DATETIME_FORMAT)
           ^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/utils/data.py", line 298, in now_datetime
    dt = convert_utc_to_system_timezone(datetime.datetime.utcnow())
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/utils/data.py", line 338, in convert_utc_to_system_timezone
    time_zone = get_system_timezone()
                ^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/utils/data.py", line 319, in get_system_timezone
    return frappe.cache.get_value("time_zone", _get_system_timezone)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/utils/redis_wrapper.py", line 100, in get_value
    val = generator()
          ^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/utils/data.py", line 312, in _get_system_timezone
    return frappe.get_system_settings("time_zone") or "Asia/Kolkata"  # Default to India ?!
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/__init__.py", line 2300, in get_system_settings
    local.system_settings = get_cached_doc("System Settings")
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/__init__.py", line 1137, in get_cached_doc
    doc = get_doc(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/__init__.py", line 1265, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/model/document.py", line 80, in get_doc
    controller = get_controller(doctype)
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/model/base_document.py", line 66, in get_controller
    return import_controller(doctype)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/model/base_document.py", line 88, in import_controller
    class_overrides = frappe.get_hooks("override_doctype_class")
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/__init__.py", line 1573, in get_hooks
    hooks = _dict(_load_app_hooks())
                  ^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/__init__.py", line 1542, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/__init__.py", line 1408, in get_module
    return importlib.import_module(modulename)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'hilltop.hooks'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/app.py", line 128, in application
    response = handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/app.py", line 320, in handle_exception
    allow_traceback = frappe.get_system_settings("allow_error_traceback") if frappe.db else False
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/__init__.py", line 2300, in get_system_settings
    local.system_settings = get_cached_doc("System Settings")
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/__init__.py", line 1137, in get_cached_doc
    doc = get_doc(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/__init__.py", line 1265, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/model/document.py", line 80, in get_doc
    controller = get_controller(doctype)
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/model/base_document.py", line 66, in get_controller
    return import_controller(doctype)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/model/base_document.py", line 88, in import_controller
    class_overrides = frappe.get_hooks("override_doctype_class")
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/__init__.py", line 1573, in get_hooks
    hooks = _dict(_load_app_hooks())
                  ^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/__init__.py", line 1542, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/__init__.py", line 1408, in get_module
    return importlib.import_module(modulename)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'hilltop.hooks'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/app.py", line 142, in application
    run_after_request_hooks(request, response)
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/app.py", line 157, in run_after_request_hooks
    for after_request_task in frappe.get_hooks("after_request"):
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/__init__.py", line 1573, in get_hooks
    hooks = _dict(_load_app_hooks())
                  ^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/__init__.py", line 1542, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amreen/erp/frappe-bench/apps/frappe/frappe/__init__.py", line 1408, in get_module
    return importlib.import_module(modulename)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'hilltop.hooks'
2024-02-01 18:18:47,046 ERROR frappe New Exception collected in error log
Site: hilltop
Form Dict: {}
2024-02-01 18:18:47,046 ERROR frappe New Exception collected in error log
Site: hilltop
Form Dict: {}
2024-02-01 18:18:47,046 ERROR frappe New Exception collected in error log
Site: hilltop
Form Dict: {}
2024-02-01 18:18:47,046 ERROR frappe New Exception collected in error log
Site: hilltop
Form Dict: {}
2024-02-01 18:18:47,731 ERROR frappe New Exception collected in error log
Site: hilltop
Form Dict: {}
2024-02-01 18:18:47,747 ERROR frappe New Exception collected in error log
Site: hilltop
Form Dict: {}
2024-02-01 18:18:47,762 ERROR frappe New Exception collected in error log
Site: hilltop
Form Dict: {}
2024-02-01 18:18:47,810 ERROR frappe New Exception collected in error log
Site: hilltop
Form Dict: {}
2024-02-01 18:18:47,820 ERROR frappe New Exception collected in error log
Site: hilltop
Form Dict: {}
2024-02-01 18:18:47,822 ERROR frappe New Exception collected in error log
Site: hilltop
Form Dict: {}
2024-02-01 18:18:47,831 ERROR frappe New Exception collected in error log
Site: hilltop
Form Dict: {}
2024-02-01 18:18:47,841 ERROR frappe New Exception collected in error log
Site: hilltop
Form Dict: {}
2024-02-01 18:18:48,542 ERROR frappe New Exception collected in error log
Site: hilltop
Form Dict: {}
2024-02-01 18:18:48,730 ERROR frappe New Exception collected in error log
Site: hilltop
Form Dict: {}
2024-02-01 18:18:48,757 ERROR frappe New Exception collected in error log
Site: hilltop
Form Dict: {}
2024-02-01 18:18:48,767 ERROR frappe New Exception collected in error log
Site: hilltop
Form Dict: {}
2024-02-01 18:18:48,767 ERROR frappe New Exception collected in error log
Site: hilltop
Form Dict: {}
2024-02-01 18:20:04,435 ERROR frappe New Exception collected in error log
Site: hilltop
Form Dict: {}
2024-02-01 18:20:04,569 ERROR frappe New Exception collected in error log
Site: hilltop
Form Dict: {}
